language: c++

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32 -extension GLX"
  - "export AUDIODEV=null"
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib git openfl https://github.com/openfl/openfl
  - haxelib git lime-tools https://github.com/openfl/lime-tools
  - haxelib git hxlibc https://github.com/openfl/hxlibc
  - haxelib git lime https://github.com/openfl/lime
  - haxelib git lime-build https://github.com/openfl/lime-build
  - haxelib install munit
  - haxelib install format
  - haxelib install svg
  - git clone https://github.com/openfl/openfl-validation ~/openfl-validation
  - haxelib dev openfl-native $(pwd)

script:
  - haxelib run openfl rebuild linux,tools
  - haxelib run openfl test ~/openfl-validation linux
  #- haxelib run openfl test ~/openfl-validation neko
